In [1]:
import numpy as np

In [2]:
#creating arrays from python list

arr = np.array([1,2,3,4])
print(arr)

[1 2 3 4]


In [5]:
#with default values arrays

# for all default zeros value 
zeros = np.zeros((3,3))
print(zeros)


#for all default ones value
ones = np.ones((3,3))
print("\n",ones)

# another one
filled_array = np.full((2,3,),7)
print("\n",filled_array)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

 [[7 7 7]
 [7 7 7]]


In [10]:
#creating sequences of numbers in numpy
#arange()
#arange(start, stop, step)

sequence_of_series = np.arange(1,12,2)
print(sequence_of_series)

[ 1  3  5  7  9 11]


In [ ]:
#creating identity matrices
#eye(size)

identity_matrix = np.eye(4)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]


In [23]:
#checking attributes - shape, size & ndin - number of dimension

arr_2d = np.array([[1,2,3],
                  [4,5,6]])
print("Shape:",arr_2d.shape)
print("size:",arr_2d.size)
print("size:",arr_2d.ndim)

arr_ndim = np.array([[[1,2],[3,4],[5,6],[7,8]]])
print("size:",arr_ndim.ndim)

Shape: (2, 3)
size: 6
size: 2
size: 3


In [31]:
#dtype - data-type of elements

arr_dataType = np.array([1,2,3.5,4,5,6])
print("Data Type:",arr_dataType.dtype)

# change data type - astype(new.type)
brr = np.array([1.2,2.3,3.4,4.5])
print("before data type convert:",brr)
print(brr.dtype)
int_brr = brr.astype(int)
print("\nAfter data type convert:",int_brr)
print(int_brr.dtype)

Data Type: float64
before data type convert: [1.2 2.3 3.4 4.5]
float64

After data type convert: [1 2 3 4]
int64


In [36]:
# mathematicals operation on numpy array

num = np.array([1,2,3,4,5,6])
print(num + 5)
print(num - 5)
print(num * 5)
print(num / 5)
print(num ** 5)

[ 6  7  8  9 10 11]
[-4 -3 -2 -1  0  1]
[ 5 10 15 20 25 30]
[0.2 0.4 0.6 0.8 1.  1.2]
[   1   32  243 1024 3125 7776]


In [ ]:
#aggregation function -  data me se summary nikalna