In [2]:
import numpy as np

In [2]:
#creating arrays from python list

arr = np.array([1,2,3,4])
print(arr)

[1 2 3 4]


In [5]:
#with default values arrays

# for all default zeros value 
zeros = np.zeros((3,3))
print(zeros)


#for all default ones value
ones = np.ones((3,3))
print("\n",ones)

# another one
filled_array = np.full((2,3,),7)
print("\n",filled_array)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

 [[7 7 7]
 [7 7 7]]


In [10]:
#creating sequences of numbers in numpy
#arange()
#arange(start, stop, step)

sequence_of_series = np.arange(1,12,2)
print(sequence_of_series)

[ 1  3  5  7  9 11]


In [ ]:
#creating identity matrices
#eye(size)

identity_matrix = np.eye(4)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]


In [23]:
#checking attributes - shape, size & ndin - number of dimension

arr_2d = np.array([[1,2,3],
                  [4,5,6]])
print("Shape:",arr_2d.shape)
print("size:",arr_2d.size)
print("size:",arr_2d.ndim)

arr_ndim = np.array([[[1,2],[3,4],[5,6],[7,8]]])
print("size:",arr_ndim.ndim)

Shape: (2, 3)
size: 6
size: 2
size: 3


In [31]:
#dtype - data-type of elements

arr_dataType = np.array([1,2,3.5,4,5,6])
print("Data Type:",arr_dataType.dtype)

# change data type - astype(new.type)
brr = np.array([1.2,2.3,3.4,4.5])
print("before data type convert:",brr)
print(brr.dtype)
int_brr = brr.astype(int)
print("\nAfter data type convert:",int_brr)
print(int_brr.dtype)

Data Type: float64
before data type convert: [1.2 2.3 3.4 4.5]
float64

After data type convert: [1 2 3 4]
int64


In [36]:
# mathematicals operation on numpy array

num = np.array([1,2,3,4,5,6])
print(num + 5)
print(num - 5)
print(num * 5)
print(num / 5)
print(num ** 5)

[ 6  7  8  9 10 11]
[-4 -3 -2 -1  0  1]
[ 5 10 15 20 25 30]
[0.2 0.4 0.6 0.8 1.  1.2]
[   1   32  243 1024 3125 7776]


In [ ]:
#aggregation function -  data me se summary nikalna

agg = np.array([10,20,30,40,50,60])
print(np.sum(agg))
print(np.mean(agg))  #average
print(np.min(agg))
print(np.max(agg))
print(np.std(agg)) #standard deviation
print(np.var(agg)) #variance


210
35.0
10
60
17.07825127659933
291.6666666666667


In [8]:
# indexing

access_arr = np.array([10,20,30,40,50])
print(access_arr[0])
print(access_arr[1])
print(access_arr[2])
print(access_arr[-1])

cr = np.array([[1,2,3],[4,5,6]])
print(cr[1,2])

10
20
30
50
6


In [ ]:
# slicing

slice_arr = np.array([10,20,30,40,50])
print(slice_arr[0:3])
print(slice_arr[0:])
print(slice_arr[:4])
print(slice_arr[1:3])
print(slice_arr[1::2])
print(slice_arr[::2]) #every second element
print(slice_arr[::-1]) #reverse


[10 20 30]
[10 20 30 40 50]
[10 20 30 40]
[20 30]
[20 40]
[10 30 50]
[50 40 30 20 10]


In [ ]:
# fancy indexing

ar = np.array([10,20,30,40,50,60,70,80])
print(ar[[0,2,4,7]]) #it creates a copy



[10 30 50 80]


In [ ]:
# filtering data - ( boolean masking )

array1 = np.array([10,20,30,40,50,60,70,80])

print(array1[array1 > 25])

[30 40 50 60 70 80]


In [28]:
#reshaping and manipulating

array2 = np.array([10,20,30,40,50,60,70,80])

#reshaping does not create copy, it returns a view
reshaped_Arr = array2.reshape(4,2)

print(reshaped_Arr)

#flattering array
array3 = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(array3.ravel()) #it returns a view
print(array3.flatten()) # it create a copy

[[10 20]
 [30 40]
 [50 60]
 [70 80]]
[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [ ]:
#Advanced numpy - add 
#np.inerst(array, index, value, axis=None), in 2d if axis = 0 row wise and if axis = 1 column wise
# and if axis = None then it insert an element on flattend version


arr = np.array([10,20,30,40,50,60,70,80])
print(arr)
new_Arr = np.insert(arr, 2, 100)
print(new_Arr)


brr = np.array([[1,2],[4,5]])
print("\n",brr)
new_brr = np.insert(brr, 1, [5,6], axis=1)
print("\ncolumn wise",new_brr)
new_brr = np.insert(brr, 1, [5,6], axis=0)
print("\n row wise",new_brr)
new_brr = np.insert(brr, 1, [5,6], axis=None)
print("\ninserting on flattered version",new_brr)

[10 20 30 40 50 60 70 80]
[ 10  20 100  30  40  50  60  70  80]

 [[1 2]
 [4 5]]

 [[1 5 2]
 [4 6 5]]

 [[1 2]
 [5 6]
 [4 5]]

 [1 5 6 2 4 5]


In [39]:
#apppend

arr = np.array([10,20,30])
new_arr = np.append(arr, [40,50,60])

print(new_arr)

[10 20 30 40 50 60]


In [ ]:
# merge 
arr = np.array([10,20,30],[4,5,6])
brr = np.array([40,50,60],)

merged_arr = np.concatenate((arr, brr))
print(merged_arr)

[10 20 30 40 50 60]


In [ ]:
# removing element - it retuns new array

arr = np.array([10,20,30,40,50,60])
print(arr)
print(np.delete(arr,2))


arr2 = np.array([[10,20,30],[40,50,60]])
print("\n",arr2)
print(np.delete(arr2,0,axis=0))

[10 20 30 40 50 60]
[10 20 40 50 60]

 [[10 20 30]
 [40 50 60]]
[[40 50 60]]


In [51]:
#stacking - vstack() row wise, hstack column wise

arr = np.array([1,2,3])
arr2 = np.array([4,5,6])

print(np.vstack((arr, arr2))) #vertically stacking
print(np.hstack((arr, arr2))) #horizontally stacking


[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [57]:
#splitting array - np.split() equal

arr2 = np.array([10,20,30,40,50,60])

print(np.split(arr2,3))

[array([10, 20]), array([30, 40]), array([50, 60])]


In [65]:
#broadcasting

prices = np.array([100,200,300])

discount = 10
final_prices = prices - (prices * discount/100)
print(final_prices)

[ 90. 180. 270.]


In [67]:
a = np.array([1,2,3,4])
res = a * 2
print(res)

matrix = np.array([[1,2,3],[4,5,6]])
vector = np.array([10,20,30])
result = matrix * vector
print(result)

[2 4 6 8]
[[ 10  40  90]
 [ 40 100 180]]
