In [ ]:
#practice of numpy
import numpy as np

In [ ]:
arr = np.array([1,2,3,4])
print("Numpy array:",arr)   #also called a vector


# default values in numpy
arr1 = np.zeros((4,4))
print("\nZeros Matrix:",arr1)

arr2 = np.ones((3,3))
print("\nOnes Matrix:",arr2)

arr3 = np.full((3,2),5)
print('\nSpecific Number Matrix:',arr3)

arr4 = np.random.random((2,3)) #random always create a value between 0 and 1
print('\nRandom Matrix:',arr4)

arr5 = np.arange(0,11,2)  #sequence of an array
print("\nArange Array:",arr5)

arr6 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("\n2D Array:\n",arr6)

arr7 = np.array([[[1,2],[3,4]],
                 [[5,6],[7,8]]])
print("\nTensor Array:\n",arr7) #also called a 3D array

arr8 = np.eye(4) #identity matrix
print('\nIdentity Matrix:\n',arr8)



Numpy array: [1 2 3 4]

Zeros Matrix: [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

Ones Matrix: [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

Specific Number Matrix: [[5 5]
 [5 5]
 [5 5]]

Random Matrix: [[0.25041792 0.74006043 0.58884406]
 [0.58087605 0.83647713 0.34432255]]

Arange Array: [ 0  2  4  6  8 10]

2D Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Tensor Array:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]

Identity Matrix:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [25]:
#array properties

arr = np.array([[1,2,3],[4,5,6]])
print("\nShape:",arr.shape)  #shape of an array
print("Size:",arr.size)    #total number of elements in an array
print("Dimension:",arr.ndim)  #number of dimensions
print("Data-Type:",arr.dtype) #data type of an array
print("Item Size:",arr.itemsize) #size of each element in bytes
print("Type:",type(arr)) #type of an array


Shape: (2, 3)
Size: 6
Dimension: 2
Data-Type: int64
Item Size: 8
Type: <class 'numpy.ndarray'>


In [31]:
# array reshaping
arr = np.arange(12)
print(arr)

reshaped_Arr = arr.reshape(3,4) # 3 rows and 4 columns
print("\nReshaped Array:\n",reshaped_Arr)

flattered_arr = reshaped_Arr.flatten() #convert any dimension to 1D array - it returns a copy of original array
print("\nFlattered Array:",flattered_arr)

revel_arr = reshaped_Arr.ravel() #convert any dimension to 1D array - it returns a view of original array
print("\nRavel Array:",revel_arr)

transpose_arr = reshaped_Arr.T #transpose of an array
print("\nTranspose of an Array:\n",transpose_arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11]

Reshaped Array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Flattered Array: [ 0  1  2  3  4  5  6  7  8  9 10 11]

Ravel Array: [ 0  1  2  3  4  5  6  7  8  9 10 11]

Transpose of an Array:
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [65]:
#slicing and accessing elements
arr = np.array([1,2,3,4,5,6,7,8,9])
print(arr[5:])
print(arr[2:7])
print(arr[0::2])
print(arr[::-1])
print(arr[-3])
#fancy indexing
print(arr[[2,5,7,0]])

arr_2d = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9],
                   [10,11,12]])
print("\n",arr_2d[1,2]) # each element access from an matrix
print(arr_2d[1]) # row access 0 based indexing
print(arr_2d[-1])  # access last row using negative one
#slicing
print("\n",arr_2d[1:]) 
print("\n",arr_2d[1:-1])
print("\n",arr_2d[::-1])  

[6 7 8 9]
[3 4 5 6 7]
[1 3 5 7 9]
[9 8 7 6 5 4 3 2 1]
7
[3 6 8 1]

 6
[4 5 6]
[10 11 12]

 [[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

 [[4 5 6]
 [7 8 9]]

 [[10 11 12]
 [ 7  8  9]
 [ 4  5  6]
 [ 1  2  3]]


In [63]:
unsorted_arr = np.array([10,5,2,9,1,20,41,3,23,51,39,28,6,17,35])
print('Sorted array:',np.sort(unsorted_arr))

unsorted_arr_2d = np.array([[10,5,2],
                            [9,1,20],
                            [41,3,23]])
print('\nSorted 2D array:\n',np.sort(unsorted_arr_2d,axis=1)) #sort each row
print('\nSorted 2D array:\n',np.sort(unsorted_arr_2d,axis=0)) #sort each column

Sorted array: [ 1  2  3  5  6  9 10 17 20 23 28 35 39 41 51]

Sorted 2D array:
 [[ 2  5 10]
 [ 1  9 20]
 [ 3 23 41]]

Sorted 2D array:
 [[ 9  1  2]
 [10  3 20]
 [41  5 23]]


In [66]:
#numercial operations
arr = np.array([1,2,3,4,5,6])
print("Original Array:",arr)
print("Addition:",arr+5)
print("Subtraction:",arr-2)
print("Multiplication:",arr*3)
print("Division:",arr/2)
print("Exponent:",arr**2)

Original Array: [1 2 3 4 5 6]
Addition: [ 6  7  8  9 10 11]
Subtraction: [-1  0  1  2  3  4]
Multiplication: [ 3  6  9 12 15 18]
Division: [0.5 1.  1.5 2.  2.5 3. ]
Exponent: [ 1  4  9 16 25 36]


In [73]:
#aggregation functions
arr = np.array([10,20,30,40,50])
print("Original Array:",arr)
print("Sum:",np.sum(arr))
print("Mean:",np.mean(arr))
print("count:",np.count_nonzero(arr))
print("Minimum:",np.min(arr))
print("Maximum:",np.max(arr))
print("Standard Deviation:",np.std(arr))
print("Varience:",np.var(arr))

Original Array: [10 20 30 40 50]
Sum: 150
Mean: 30.0
count: 5
Minimum: 10
Maximum: 50
Standard Deviation: 14.142135623730951
Varience: 200.0


In [84]:
# filtering data 
arr = np.array([10,25,30,45,50,65,70,85,90])
filter_arr = arr[arr>50]
print("Filtered Array:",filter_arr)
filter_arr = arr[(arr>50) & (arr<85)]
print("Filtered Array:",filter_arr)
filter_arr3 = arr[arr % 2 == 0]
print("Filtered Array:",filter_arr3)

Filtered Array: [65 70 85 90]
Filtered Array: [65 70]
Filtered Array: [10 30 50 70 90]


In [ ]:
#advanced concepts inserting values using numpy functions
arr = np.array([1,2,3,4,5])
print("Original Array:",arr)

new_arr= np.insert(arr,3,55) #insert 100 at index 3
print("New Array after adding 5:",new_arr)

arr_2d = np.array([[1,2,3],
                   [4,5,6],
                     [7,8,9]])
print("Original 2D Array:\n",arr_2d)
new_arr_2d = np.insert(arr_2d,1,55,axis=0) #insert 55 at index 1 row wise
print("New 2D Array after adding 55 row wise:\n",new_arr_2d)

new_arr_2d = np.insert(arr_2d,1,[12,32,52],axis=0) 
print("New 2D Array after adding row wise:\n",new_arr_2d)

new_arr_2d = np.insert(arr_2d,1,[12,32,52],axis=1) #column wise insert
print("New 2D Array after adding column wise:\n",new_arr_2d)

new_arr_2d = np.insert(arr_2d,1,[12,32,52],axis=None) #axis none means a vector - insert in vector
print("New 2D Array:\n",new_arr_2d)

# reshaped_Arr = new_arr_2d.reshape(4,3)
# print("Reshped arr:\n",reshaped_Arr)

Original Array: [1 2 3 4 5]
New Array after adding 5: [ 1  2  3 55  4  5]
Original 2D Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
New 2D Array after adding 55 row wise:
 [[ 1  2  3]
 [55 55 55]
 [ 4  5  6]
 [ 7  8  9]]
New 2D Array after adding row wise:
 [[ 1  2  3]
 [12 32 52]
 [ 4  5  6]
 [ 7  8  9]]
New 2D Array after adding column wise:
 [[ 1 12  2  3]
 [ 4 32  5  6]
 [ 7 52  8  9]]
New 2D Array:
 [ 1 12 32 52  2  3  4  5  6  7  8  9]
Reshped arr:
 [[ 1 12 32]
 [52  2  3]
 [ 4  5  6]
 [ 7  8  9]]


In [ ]:
#append
arr = np.array([1,2,3,4,5])
print("Append new arr:",np.append(arr, [6,7,8,9]))

arr_2d = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])
print("Append new 2D arr:\n",np.append(arr_2d, [[10,11,12]], axis=0)) #row wise append
print("Append new 2D arr:\n",np.append(arr_2d, [[10],[11],[12]], axis=1)) #column wise append
print("Append new 2D arr:\n",np.append(arr_2d, [[10,11,12]], axis=None)) #vector append

Append new arr: [1 2 3 4 5 6 7 8 9]
Append new 2D arr:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Append new 2D arr:
 [[ 1  2  3 10]
 [ 4  5  6 11]
 [ 7  8  9 12]]
Append new 2D arr:
 [ 1  2  3  4  5  6  7  8  9 10 11 12]


In [ ]:
#merge - use concatenate function
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

arr3 = np.concatenate((arr1,arr2))
print("Merged Array:",arr3)

Merged Array: [1 2 3 4 5 6]


In [113]:
#removing elements - use delete function it returns a new array with the specified subarray deleted from the input array.
arr = np.array([1,2,3,4,5,6,7,8,9])
new_arr = np.delete(arr,3) #delete element at index 3
print("New Array after deleting an element:",new_arr)

arr2 = np.array([[1,2,3,4],
                [5,6,7,8],
                [9,10,11,12]])
new_arr2 = np.delete(arr2,0,axis=0)
print("New 2D Array after deleting row 0:\n",new_arr2)
new_arr2 = np.delete(arr2,1,axis=1)
print("New 2D Array after deleting column 1:\n",new_arr2)
#it can also delete multiple values
new_arr2 = np.delete(arr2,[0,1],axis=1)
print("New 2D Array after deleting column 0 and 1:\n",new_arr2)
new_arr2 = np.delete(arr2,[0,1],axis=0)
print("New 2D Array after deleting rows 0 and 1:\n",new_arr2)

New Array after deleting an element: [1 2 3 5 6 7 8 9]
New 2D Array after deleting row 0:
 [[ 5  6  7  8]
 [ 9 10 11 12]]
New 2D Array after deleting column 1:
 [[ 1  3  4]
 [ 5  7  8]
 [ 9 11 12]]
New 2D Array after deleting column 0 and 1:
 [[ 3  4]
 [ 7  8]
 [11 12]]
New 2D Array after deleting rows 0 and 1:
 [[ 9 10 11 12]]


In [ ]:
#stacking - use vstack and hstack
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
vstack_arr = np.vstack((arr1,arr2))
print("Vertical Stack:\n",vstack_arr)
hstack_arr = np.hstack((arr1,arr2)) #horizontal stack it like merge
print("Horizontal Stack:\n",hstack_arr)

Vertical Stack:
 [[1 2 3]
 [4 5 6]]
Horizontal Stack:
 [1 2 3 4 5 6]


In [118]:
#splitting - use array_split
arr = np.array([1,2,3,4,5,6,7,8,9])
split_arr = np.array_split(arr,3) #split array into 3 sub arrays
print("Split Array:",split_arr)
print("Split First Array:",split_arr[0]) #accessing first sub array
print("Split Second Array:",split_arr[1]) #accessing second sub array
print("Split Third Array:",split_arr[2]) #accessing third sub array

Split Array: [array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]
Split First Array: [1 2 3]
Split Second Array: [4 5 6]
Split Third Array: [7 8 9]


In [119]:
#broadcasting - use broadcasting to perform operations on arrays of different shapes
a = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
b = np.array([1,0,1])
print("Original Array a:\n",a)
print("Original Array b:\n",b)
print("Broadcasted Array:\n",a+b) #add b to each row of a
print("Broadcasted Array:\n",a*b) #multiply b to each row of a

Original Array a:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Original Array b:
 [1 0 1]
Broadcasted Array:
 [[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]]
Broadcasted Array:
 [[1 0 3]
 [4 0 6]
 [7 0 9]]
