### Numpy Array operations

In [2]:
import numpy as np

In [ ]:
arr = np.array([1,2,3,4,5,6,7,8,9])
print("Basic Slicing",arr[2:7])
print("With Step",arr[1:8:2])   
print("Negative indexing",arr[-3])

Basic Slicing [3 4 5 6 7]
With Step [2 4 6 8]
Negative indexing 7


In [ ]:
arr_2d = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])

print("Specific element:",arr_2d[1,2])
print("Entrie row:",arr_2d[1])
print("Entrie column:",arr_2d[:,1])

Specific element: 6
Entrie row: [4 5 6]
Entrie row: [2 5 8]


## Sorting

In [ ]:
unsorted = np.array([3,4,51,6,7,9,4,2,5,6])
print("Sorted array:",np.sort(unsorted))

arr_2d_unsorted = np.array([[3,1],[1,2],[2,3]])
print("Sorted 2D array by column:",np.sort(arr_2d_unsorted, axis=0))    #top to bottom sorting

Sorted array: [ 2  3  4  4  5  6  6  7  9 51]
Sorted 2D array by column: [[1 1]
 [2 2]
 [3 3]]


## Filtering

In [11]:
numbers = np.array([1,2,3,4,5,6,7,8,9,10])
even_number = numbers[numbers % 2 == 0]
print("Even numbers:", even_number)

Even numbers: [ 2  4  6  8 10]


## filter with mask

In [12]:
mask = numbers > 5
print("Number greater than 5:",numbers[mask])

Number greater than 5: [ 6  7  8  9 10]


## Fancy indexing vs np.where()

In [20]:
indices = [0,2,4]
print(numbers[indices])

where_res = np.where(numbers > 5)
print(where_res)
print("NP where:", numbers[where_res])

[1 3 5]
(array([5, 6, 7, 8, 9]),)
NP where: [ 6  7  8  9 10]


In [27]:
condition = np.where(numbers > 5, numbers*4, numbers)
print(condition)
check = np.where(numbers > 5, "True", "False")
print(check)

[ 1  2  3  4  5 24 28 32 36 40]
['False' 'False' 'False' 'False' 'False' 'True' 'True' 'True' 'True'
 'True']


### Adding and removing data

In [30]:
arr1 = np.array([1,2,3])
arr_2 = np.array([4,5,6])

combined = np.concatenate((arr1, arr_2))
print(combined)

[1 2 3 4 5 6]


### Array compatibility

In [33]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.array([7,8,9])

print("Compatibility shpaes:", a.shape == b.shape)

Compatibility shpaes: True


In [37]:
original = np.array([[1,2], [3,4]])
new_row = np.array([[5,6]])

with_new_row = np.vstack((original, new_row))
print(original)
print("\n",with_new_row)


new_col = np.array([[7],[8]])
with_new_col = np.hstack((original, new_col))
print("\n",with_new_col)

[[1 2]
 [3 4]]

 [[1 2]
 [3 4]
 [5 6]]

 [[1 2 7]
 [3 4 8]]


In [39]:
arr = np.array([1,2,3,4,5])

deleted = np.delete(arr, 2)
print("Array after deletion:",deleted)

Array after deletion: [1 2 4 5]
