In [ ]:
import numpy as np

# Columns: [Math, Science, English]
scores = np.array([
    [88, 92, 80],
    [78, 85, 90],
    [92, 88, 95],
    [70, 75, 65],
    [95, 90, 98]
])

print(scores)

[[88 92 80]
 [78 85 90]
 [92 88 95]
 [70 75 65]
 [95 90 98]]


In [74]:
# Level 1 (Basic)
# Print the Math scores (first column).
print("Maths column:",scores[:,0])
print("*****************************************************")

# Print the Science + English scores together.
total_score = (scores[:,0] + scores[:,1]).sum()
print("Total scores of Maths and Science:",total_score)
print("*****************************************************")

#Find the shape of the dataset.
print("Shape of dataset:",scores.shape)
print("*****************************************************")

# Find the average score for each subject (column mean).
avg_maths = scores[:,0].mean()
avg_science = scores[:,1].mean()
avg_english = scores[:,2].mean()
print(f"Average score - Maths: {avg_maths}, Science: {avg_science}, English: {avg_english}")
print("*****************************************************")

# Find the highest English score.
print("Highest english score:",scores[:,2].max())

Maths column: [88 78 92 70 95]
*****************************************************
Total scores of Maths and Science: 853
*****************************************************
Shape of dataset: (5, 3)
*****************************************************
Average score - Maths: 84.6, Science: 86.0, English: 85.6
*****************************************************
Highest english score: 98


In [75]:
#Level 2 (Intermediate)
# Find the total score per student (row sums).
total_score = scores.sum(axis=1)
print("The total score per student:",total_score)
print("*****************************************************")

# Find the student with the highest total score.
print("The student with the highest total score:",scores.sum(axis=1).max())
print("*****************************************************")

#Normalize all scores (scale between 0 and 1).
min_value = scores.min()
max_value = scores.max()
normalized_score = (scores - min_value) / (max_value - min_value)
print("Normalize all scores (scale between 0 and 1):\n",normalized_score)
print("*****************************************************")

# Find the subject in which students performed best on average.
average_scores = scores.mean(axis=0)
subjects = ["Math", "Science", "English"]
best_subject_index = np.argmax(average_scores)   #argmax - provide maximum element index
best_subject = subjects[best_subject_index]
print("The subject in which students performed best on average:",best_subject)

#Replace all scores < 80 with 80 (bonus marks 😎).
# scores[scores < 80] = 80
# print(scores)
# OR 
updated_score = np.where(scores < 80, 80, scores)
print(updated_score)

The total score per student: [260 253 275 210 283]
*****************************************************
The student with the highest total score: 283
*****************************************************
Normalize all scores (scale between 0 and 1):
 [[0.6969697  0.81818182 0.45454545]
 [0.39393939 0.60606061 0.75757576]
 [0.81818182 0.6969697  0.90909091]
 [0.15151515 0.3030303  0.        ]
 [0.90909091 0.75757576 1.        ]]
*****************************************************
The subject in which students performed best on average: Science
[[88 92 80]
 [80 85 90]
 [92 88 95]
 [80 80 80]
 [95 90 98]]


In [ ]:
# Level 3 (Advanced)
# Compute the correlation between Math and Science scores.
math = scores[:,0]
science = scores[:,1]

correlation = np.corrcoef(math, science)
print(correlation)
print("Correlation between Math and Science:",correlation[0, 1])
print("*****************************************************")

#Sort students by their Math score.
maths = scores[:,0]
index = np.argsort(maths)    # provide all element index in sorted form
print(index)
new_score = scores[index]
print("Students sorted by Math score:\n",new_score)

print("*****************************************************")
# Create a boolean mask of all students who scored >90 in all subjects.
scores = np.array([
    [88, 92, 80],
    [78, 85, 90],
    [92, 88, 95],
    [70, 75, 65],
    [95, 90, 98]
])
mask = np.all(scores>90, axis=1)
# print(mask)
qualfied_std = scores[mask]
print("Students with >90 in all subjects:\n", qualfied_std)

print("*****************************************************")

#Add a new student [85, 89, 92] to the dataset.
add_new_std = np.insert(scores,4,[[85, 89, 92]], axis=0) #for insert axis=0 means row wise insert...
print(add_new_std)

[[1.         0.88072525]
 [0.88072525 1.        ]]
Correlation between Math and Science: 0.8807252531315408
*****************************************************
[3 1 0 2 4]
Students sorted by Math score:
 [[70 75 65]
 [78 85 90]
 [88 92 80]
 [92 88 95]
 [95 90 98]]
*****************************************************
Students with >90 in all subjects:
 []
*****************************************************
[[88 92 80]
 [78 85 90]
 [92 88 95]
 [70 75 65]
 [85 89 92]
 [95 90 98]]
